import pygame

WIDTH, HEIGHT = 500, 650

logo_image = pygame.image.load('images/logo.png')
logo_image = pygame.transform.scale(logo_image, (241, 113))
menuline = pygame.image.load('images/sidemenuline.png')
menuline = pygame.transform.scale(menuline, (147, 1))
welcomuser = pygame.image.load('images/welcome.png')
welcomuser = pygame.transform.scale(welcomuser, (255, 39))
bgdoodles = pygame.image.load('images/bgdoodles.png')
bgdoodles = pygame.transform.scale(bgdoodles, (WIDTH, HEIGHT))
difftitle = pygame.image.load('images/difftitle.png')
difftitle = pygame.transform.scale(difftitle, (456, 150))
difficultybg = pygame.image.load('images/difficultybg.png')
difficultybg = pygame.transform.scale(difficultybg, (WIDTH, HEIGHT))
patternstitle = pygame.image.load('images/patternstitle.png')
patternstitle = pygame.transform.scale(patternstitle, (456, 193))
seqtitle = pygame.image.load('images/seqtitle.png')
seqtitle = pygame.transform.scale(seqtitle, (456, 202))
howtoplaytitle = pygame.image.load('images/howtoplaydifftitle.png')
howtoplaytitle = pygame.transform.scale(howtoplaytitle, (178, 68))

image1 = pygame.image.load('spot the difference images/image1.png')
image1 = pygame.transform.scale(image1, (400, 267))
image1changed = pygame.image.load('spot the difference images/image1changed.png')
image1changed = pygame.transform.scale(image1changed, (400, 267))
image2 = pygame.image.load('spot the difference images/image2.png')
image2 = pygame.transform.scale(image2, (400, 267))
image2changed = pygame.image.load('spot the difference images/image2changed.png')
image2changed = pygame.transform.scale(image2changed, (400, 267))
image3 = pygame.image.load('spot the difference images/image3.png')
image3 = pygame.transform.scale(image3, (400, 267))
image3changed = pygame.image.load('spot the difference images/image3changed.png')
image3changed = pygame.transform.scale(image3changed, (400, 267))
image4 = pygame.image.load('spot the difference images/image4.png')
image4 = pygame.transform.scale(image4, (400, 267))
image4changed = pygame.image.load('spot the difference images/image4changed.png')
image4changed = pygame.transform.scale(image4changed, (400, 267))
image5 = pygame.image.load('spot the difference images/image5.png')
image5 = pygame.transform.scale(image5, (400, 267))
image5changed = pygame.image.load('spot the difference images/image5changed.png')
image5changed = pygame.transform.scale(image5changed, (400, 267))